# Generated by Django 6.0.4 on 2026-04-24 22:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Nombre/Razón Social')),
                ('customer_type', models.CharField(choices=[('individual', 'Cliente Individual'), ('business', 'Empresa')], default='individual', max_length=20, verbose_name='Tipo de Cliente')),
                ('id_number', models.CharField(max_length=50, unique=True, verbose_name='Cédula/NIT')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Correo')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Ingrese un teléfono válido', regex='^\\+?[\\d\\s\\-()]+$')], verbose_name='Teléfono')),
                ('mobile', models.CharField(blank=True, max_length=20, verbose_name='Celular')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('state', models.CharField(max_length=100, verbose_name='Departamento')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Código Postal')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Límite de Crédito')),
                ('payment_terms', models.CharField(blank=True, max_length=100, verbose_name='Términos de Pago')),
                ('contact_person', models.CharField(blank=True, max_length=200, verbose_name='Persona de Contacto')),
                ('contact_position', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['id_number'], name='customers_c_id_numb_543491_idx'), models.Index(fields=['email'], name='customers_c_email_4fdeb3_idx'), models.Index(fields=['is_active'], name='customers_c_is_acti_91d305_idx')],
            },
        ),
    ]
