<?php

return [
    ['id'=>1,'name'=>'iPhone 15 Pro Max 256GB','description'=>'Smartphone premium con cámara Pro, titanio y pantalla OLED adaptativa.','price'=>1199,'offer_price'=>1099,'stock'=>18,'sku'=>'APL-IP15PM-256','images'=>['https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=900&q=80'],'rating'=>4.9,'specs'=>['Pantalla'=>'6.7 OLED','Chip'=>'A17 Pro','Garantía'=>'12 meses'],'brand'=>'Apple','category'=>'Celulares','subcategory'=>'Smartphones','variants'=>['color'=>['Titanio','Azul'],'almacenamiento'=>['256GB','512GB']],'featured'=>1,'status'=>'active'],
    ['id'=>2,'name'=>'Samsung Galaxy S24 Ultra','description'=>'Teléfono Android flagship con S Pen, IA integrada y zoom óptico avanzado.','price'=>1299,'offer_price'=>1189,'stock'=>24,'sku'=>'SMS-S24U-512','images'=>['https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?auto=format&fit=crop&w=900&q=80'],'rating'=>4.8,'specs'=>['Pantalla'=>'6.8 AMOLED','Memoria'=>'12GB RAM','IA'=>'Galaxy AI'],'brand'=>'Samsung','category'=>'Celulares','subcategory'=>'Smartphones','variants'=>['color'=>['Negro','Gris'],'almacenamiento'=>['256GB','512GB']],'featured'=>1,'status'=>'active'],
    ['id'=>3,'name'=>'MacBook Pro 14 M3 Pro','description'=>'Laptop profesional para desarrollo, edición y productividad intensiva.','price'=>1999,'offer_price'=>1899,'stock'=>11,'sku'=>'APL-MBP14-M3P','images'=>['https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=900&q=80'],'rating'=>4.9,'specs'=>['CPU'=>'M3 Pro','RAM'=>'18GB','SSD'=>'512GB'],'brand'=>'Apple','category'=>'Laptops','subcategory'=>'Profesionales','variants'=>['color'=>['Space Black','Silver'],'almacenamiento'=>['512GB','1TB']],'featured'=>1,'status'=>'active'],
    ['id'=>4,'name'=>'Dell XPS 15 OLED','description'=>'Laptop Windows premium con panel OLED, chasis de aluminio y GPU dedicada.','price'=>1799,'offer_price'=>1649,'stock'=>9,'sku'=>'DLL-XPS15-OLED','images'=>['https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&w=900&q=80'],'rating'=>4.6,'specs'=>['Pantalla'=>'15.6 OLED','RAM'=>'32GB','GPU'=>'RTX Studio'],'brand'=>'Dell','category'=>'Laptops','subcategory'=>'Ultrabooks','variants'=>['color'=>['Plata'],'almacenamiento'=>['1TB']],'featured'=>1,'status'=>'active'],
    ['id'=>5,'name'=>'Apple Watch Ultra 2','description'=>'Smartwatch resistente para deporte, salud, navegación y uso diario.','price'=>799,'offer_price'=>749,'stock'=>20,'sku'=>'APL-WU2','images'=>['https://images.unsplash.com/photo-1551816230-ef5deaed4a26?auto=format&fit=crop&w=900&q=80'],'rating'=>4.7,'specs'=>['Caja'=>'Titanio 49mm','Batería'=>'Hasta 36h','Resistencia'=>'100m'],'brand'=>'Apple','category'=>'Smartwatches','subcategory'=>'Deportivo','variants'=>['color'=>['Titanio'],'tamaño'=>['49mm']],'featured'=>1,'status'=>'active'],
    ['id'=>6,'name'=>'PlayStation 5 Slim','description'=>'Consola de nueva generación con SSD ultrarrápido y mando DualSense.','price'=>499,'offer_price'=>459,'stock'=>35,'sku'=>'SNY-PS5-SLIM','images'=>['https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?auto=format&fit=crop&w=900&q=80'],'rating'=>4.8,'specs'=>['Almacenamiento'=>'1TB','Resolución'=>'4K','Control'=>'DualSense'],'brand'=>'Sony','category'=>'Consolas','subcategory'=>'Gaming','variants'=>['color'=>['Blanco'],'almacenamiento'=>['1TB']],'featured'=>1,'status'=>'active'],
    ['id'=>7,'name'=>'LG OLED C3 55 pulgadas','description'=>'Smart TV OLED 4K con negros perfectos, HDMI 2.1 y modo gaming.','price'=>1399,'offer_price'=>1199,'stock'=>8,'sku'=>'LG-OLEDC3-55','images'=>['https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=900&q=80'],'rating'=>4.7,'specs'=>['Panel'=>'OLED evo','Frecuencia'=>'120Hz','Sistema'=>'webOS'],'brand'=>'LG','category'=>'TVs','subcategory'=>'OLED','variants'=>['tamaño'=>['55','65']],'featured'=>1,'status'=>'active'],
    ['id'=>8,'name'=>'NVIDIA GeForce RTX 4070 Super','description'=>'GPU para gaming y creación con ray tracing, DLSS y gran eficiencia.','price'=>599,'offer_price'=>569,'stock'=>14,'sku'=>'NV-RTX4070S','images'=>['https://images.unsplash.com/photo-1591488320449-011701bb6704?auto=format&fit=crop&w=900&q=80'],'rating'=>4.6,'specs'=>['VRAM'=>'12GB GDDR6X','Arquitectura'=>'Ada Lovelace','Uso'=>'Gaming/IA'],'brand'=>'Asus','category'=>'Componentes PC','subcategory'=>'GPU','variants'=>['color'=>['Negro']],'featured'=>1,'status'=>'active'],
    ['id'=>9,'name'=>'Logitech MX Master 3S','description'=>'Mouse ergonómico profesional con scroll magnético y alta precisión.','price'=>99,'offer_price'=>89,'stock'=>60,'sku'=>'LOG-MXM3S','images'=>['https://images.unsplash.com/photo-1527814050087-3793815479db?auto=format&fit=crop&w=900&q=80'],'rating'=>4.7,'specs'=>['DPI'=>'8000','Conexión'=>'Bluetooth/USB','Batería'=>'70 días'],'brand'=>'Logitech','category'=>'Accesorios','subcategory'=>'Mouse','variants'=>['color'=>['Grafito','Blanco']],'featured'=>0,'status'=>'active'],
    ['id'=>10,'name'=>'Xbox Series X 1TB','description'=>'Consola 4K con Game Pass, SSD y retrocompatibilidad avanzada.','price'=>499,'offer_price'=>469,'stock'=>22,'sku'=>'MS-XBSX-1TB','images'=>['https://images.unsplash.com/photo-1621259182978-fbf93132d53d?auto=format&fit=crop&w=900&q=80'],'rating'=>4.7,'specs'=>['Resolución'=>'4K','SSD'=>'1TB','FPS'=>'Hasta 120'],'brand'=>'Microsoft','category'=>'Consolas','subcategory'=>'Gaming','variants'=>['color'=>['Negro']],'featured'=>0,'status'=>'active']
];
