# Generated by Django 6.0.4 on 2026-04-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual')], max_length=20, verbose_name='Tipo de Reporte')),
                ('report_date', models.DateField(verbose_name='Fecha del Reporte')),
                ('total_invoices', models.PositiveIntegerField(default=0)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('average_invoice', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reporte de Ventas',
                'verbose_name_plural': 'Reportes de Ventas',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(verbose_name='Fecha del Reporte')),
                ('product_name', models.CharField(max_length=300, verbose_name='Producto')),
                ('sku', models.CharField(max_length=100, verbose_name='SKU')),
                ('total_sold', models.PositiveIntegerField(default=0, verbose_name='Cantidad Vendida')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ingresos Totales')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Reporte de Producto',
                'verbose_name_plural': 'Reportes de Productos',
                'ordering': ['-total_revenue'],
                'indexes': [models.Index(fields=['report_date'], name='reports_pro_report__a747c7_idx'), models.Index(fields=['total_sold'], name='reports_pro_total_s_c0d714_idx')],
            },
        ),
    ]
