# Generated by Django 6.0.4 on 2026-04-24 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreport',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_reports', to=settings.AUTH_USER_MODEL, verbose_name='Generado por'),
        ),
        migrations.AddIndex(
            model_name='salesreport',
            index=models.Index(fields=['report_date'], name='reports_sal_report__92f498_idx'),
        ),
        migrations.AddIndex(
            model_name='salesreport',
            index=models.Index(fields=['report_type'], name='reports_sal_report__13dd85_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salesreport',
            unique_together={('report_type', 'report_date')},
        ),
    ]
